kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: okd-cleaner
  namespace: openshift-cron-jobs
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: openshift-client
              image: 'quay.io/agileio/okd-cleaner:latest'
              args:
                - /bin/sh
                - '-c'
                - ./startup.sh
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
